import { useEffect, useMemo, useState } from 'react';
import type { Team, TeamRecord } from './types';
import { inviteTeamMember, loadTeamMembers, removeTeamMember, type TeamMember, updateTeamMemberRole } from './api';

type Props = { team?: Team; records: TeamRecord[]; onOpen: (record: TeamRecord) => void };
const get = (record: TeamRecord, ...keys: string[]) => {
  for (const key of keys) { const item = record.payload[key]; if (item !== undefined && item !== null && String(item).trim()) return String(item); }
  return 'Not captured';
};
const title = (record: TeamRecord) => get(record, 'name', 'supplier_name', 'product_name', 'title', 'company_name');
const escape = (input: unknown) => String(input ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character);

function printPack(name: string, subtitle: string, sections: Array<[string, Array<[string, string]>]>) {
  const content = sections.map(([heading, rows]) => `<section><h2>${escape(heading)}</h2><table>${rows.map(([key, value]) => `<tr><th>${escape(key)}</th><td>${escape(value)}</td></tr>`).join('')}</table></section>`).join('');
  const tab = window.open('', '_blank');
  if (!tab) return;
  tab.document.write(`<!doctype html><html><head><title>${escape(name)}</title><style>body{font-family:Arial,sans-serif;color:#17394b;margin:38px}h1{margin:0;font-size:28px}p{color:#61788a}h2{font-size:14px;text-transform:uppercase;letter-spacing:.08em;border-bottom:2px solid #d8b55c;padding-bottom:7px;margin-top:25px}table{border-collapse:collapse;width:100%}th,td{padding:9px 8px;border-bottom:1px solid #dbe5e5;text-align:left}th{width:34%;color:#60798a;font-size:12px;text-transform:uppercase}@media print{body{margin:18px}}</style></head><body><h1>${escape(name)}</h1><p>${escape(subtitle)}</p>${content}<script>window.onload=()=>window.print()<\/script></body></html>`);
  tab.document.close();
}

function downloadComparison(records: TeamRecord[]) {
  const headers = ['Product', 'Supplier', 'Quoted price', 'Currency', 'MOQ', 'Lead time', 'Payment terms', 'Certificates', 'Samples'];
  const rows = records.filter((record) => ['product', 'quotation', 'quote'].includes(record.record_type)).map((record) => [title(record), get(record, 'supplier_name', 'supplier', 'company_name'), get(record, 'quoted_price', 'unit_price', 'price'), get(record, 'currency'), get(record, 'minimum_order_quantity', 'moq'), get(record, 'lead_time', 'lead_time_days'), get(record, 'payment_terms'), get(record, 'certificate', 'certificates'), get(record, 'sample_status', 'samples')]);
  const table = [headers, ...rows].map((row) => `<Row>${row.map((cell) => `<Cell><Data ss:Type="String">${escape(cell)}</Data></Cell>`).join('')}</Row>`).join('');
  const xml = `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Quote comparison"><Table>${table}</Table></Worksheet></Workbook>`;
  const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([xml], { type: 'application/vnd.ms-excel' })); link.download = 'quote-comparison.xls'; link.click(); URL.revokeObjectURL(link.href);
}

export function ProcurementCompletionTools({ team, records, onOpen }: Props) {
  const suppliers = useMemo(() => records.filter((record) => record.record_type === 'supplier'), [records]);
  const trips = useMemo(() => records.filter((record) => ['trip', 'visit_trip'].includes(record.record_type)), [records]);
  const [supplierId, setSupplierId] = useState(''); const [tripId, setTripId] = useState('');
  const [members, setMembers] = useState<TeamMember[]>([]); const [email, setEmail] = useState(''); const [role, setRole] = useState<TeamMember['role']>('member'); const [message, setMessage] = useState('');
  const admin = team?.role === 'admin';
  const loadMembers = async () => { if (!team || !admin) return; try { setMembers(await loadTeamMembers(team.id)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load team members.'); } };
  useEffect(() => { void loadMembers(); }, [team?.id, admin]);
  const supplier = suppliers.find((item) => item.record_id === supplierId) ?? suppliers[0];
  const trip = trips.find((item) => item.record_id === tripId) ?? trips[0];
  const audit = [...records].sort((a, b) => b.updated_at.localeCompare(a.updated_at)).slice(0, 12);
  const card = { background: '#f8fbfb', border: '1px solid #d9e6e5', borderRadius: 12, padding: 20, marginTop: 16 };
  return <section style={{ marginTop: 24 }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'baseline', flexWrap: 'wrap' }}><div><p className="eyebrow">CONTROL CENTER TOOLS</p><h2>Exports, team access & audit trail</h2><p className="muted">Create durable procurement packs and manage the people who can work in this team.</p></div><button type="button" className="button secondary" onClick={() => downloadComparison(records)}>Download quote comparison Excel</button></div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16 }}>
      <div style={card}><h3>Supplier profile PDF</h3><p className="muted">Print a complete profile or save it as a PDF from the print dialog.</p><select value={supplierId} onChange={(event) => setSupplierId(event.target.value)}><option value="">Select supplier</option>{suppliers.map((item) => <option key={item.record_id} value={item.record_id}>{title(item)}</option>)}</select><button type="button" className="button" disabled={!supplier} onClick={() => { if (!supplier) return; const related = records.filter((item) => get(item, 'supplier_id', 'supplier_record_id') === supplier.record_id || get(item, 'supplier_name', 'supplier') === title(supplier)); printPack(title(supplier), 'Supplier profile export', [['Supplier details', [['Country', get(supplier, 'country')], ['Hall / booth', get(supplier, 'hall', 'booth')], ['Category', get(supplier, 'category')], ['Decision', get(supplier, 'decision', 'status')], ['Shortlisted', get(supplier, 'shortlisted')]]], ['Related records', [['Contacts', String(related.filter((item) => item.record_type === 'contact').length)], ['Products and quotations', String(related.filter((item) => ['product', 'quotation', 'quote'].includes(item.record_type)).length)], ['Visits and follow-ups', String(related.filter((item) => ['meeting', 'visit', 'follow_up'].includes(item.record_type)).length)], ['Attachments', String(related.filter((item) => item.record_type === 'attachment').length)]]]]); }}>Print / save supplier PDF</button></div>
      <div style={card}><h3>Trip report PDF</h3><p className="muted">Produce a visit and follow-up report that can be shared after the fair.</p><select value={tripId} onChange={(event) => setTripId(event.target.value)}><option value="">Select trip</option>{trips.map((item) => <option key={item.record_id} value={item.record_id}>{title(item)}</option>)}</select><button type="button" className="button" disabled={!trip} onClick={() => { if (!trip) return; const related = records.filter((item) => get(item, 'trip_id', 'trip_record_id') === trip.record_id); printPack(title(trip), 'Trip report export', [['Trip summary', [['Status', get(trip, 'status')], ['Start date', get(trip, 'start_date')], ['End date', get(trip, 'end_date')], ['Notes', get(trip, 'notes')]]], ['Captured activity', [['Supplier visits', String(related.filter((item) => ['visit', 'meeting'].includes(item.record_type)).length)], ['Products', String(related.filter((item) => item.record_type === 'product').length)], ['Follow-ups', String(related.filter((item) => item.record_type === 'follow_up').length)], ['Attachments', String(related.filter((item) => item.record_type === 'attachment').length)]]]]); }}>Print / save trip PDF</button></div>
    </div>
    {admin && <div style={card}><h3>Team controls</h3><p className="muted">Roles are enforced by the team server rules: administrators manage access, members work on records, and viewers have read-only access.</p><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'end' }}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="colleague@company.com" /></label><label>Role<select value={role} onChange={(event) => setRole(event.target.value as TeamMember['role'])}><option value="member">Member</option><option value="viewer">Viewer</option><option value="admin">Administrator</option></select></label><button type="button" className="button" onClick={async () => { if (!team || !email.trim()) return; try { await inviteTeamMember(team.id, email, role); setEmail(''); setMessage('Invitation created.'); await loadMembers(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to invite this member.'); } }}>Invite member</button></div>{message && <p className="muted">{message}</p>}<div style={{ marginTop: 14, display: 'grid', gap: 8 }}>{members.map((member) => <div key={member.user_id} style={{ display: 'flex', gap: 10, justifyContent: 'space-between', flexWrap: 'wrap', alignItems: 'center', borderTop: '1px solid #d9e6e5', paddingTop: 10 }}><strong>{member.email}</strong><span style={{ display: 'flex', gap: 8 }}><select value={member.role} onChange={async (event) => { if (!team) return; try { await updateTeamMemberRole(team.id, member.user_id, event.target.value as TeamMember['role']); await loadMembers(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to change this role.'); } }}><option value="admin">Administrator</option><option value="member">Member</option><option value="viewer">Viewer</option></select><button type="button" className="button secondary" onClick={async () => { if (!team || !window.confirm(`Remove ${member.email} from this team?`)) return; try { await removeTeamMember(team.id, member.user_id); await loadMembers(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to remove this member.'); } }}>Remove</button></span></div>)}</div></div>}
    <div style={card}><h3>Activity audit trail</h3><p className="muted">Recent changes captured in this workspace. Select a record to review its full history and details.</p><div style={{ display: 'grid', gap: 8 }}>{audit.map((item) => <button type="button" key={`${item.record_type}-${item.record_id}`} className="list-card" onClick={() => onOpen(item)}><strong>{title(item)}</strong><span>{item.record_type.replaceAll('_', ' ')} · {new Date(item.updated_at).toLocaleString()}</span></button>)}</div></div>
  </section>;
}
